### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by wschwanghart** [TopoToolbox/topotoolboxr#23]
Hi, I just tried to get `topotoolboxr` running, installing it with the `devtools` function `install_github`, i.e. using`install_github("topotoolbox\topotoolboxr").

I got following message:
```
* installing *source* package 'topotoolboxr' ...
** using staged installation
** libs
gcc  -I"C:/PROGRA~1/R/R-43~1.1/include" -DNDEBUG -Ilibs/libtopotoolbox/include    -I"c:/rtools43/x86_64-w64-mingw32.static.posix/include"  -DTOPOTOOLBOX_STATICLIB   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c registerDynamicSymbol.c -o registerDynamicSymbol.o
/bin/sh: line 1: gcc: command not found
make: *** [C:/PROGRA~1/R/R-43~1.1/etc/x64/Makeconf:265: registerDynamicSymbol.o] Error 127
ERROR: compilation failed for package 'topotoolboxr'
* removing 'C:/Users/Wolf/AppData/Local/R/win-library
```

Hence, it seems that there is a problem with compilation. Or is it too early to come up with this issue?

**Comment by wkearn** [comment]
This should work. Since it claims that can't find `gcc`, my guess is that either we are making some assumptions about the C compilers that R uses on Windows or there is a problem with your R installation.

Are you currently able to install other packages that use C extensions? For example, try `install.packages("terra")` or `install.packages("spatstat")`, which use C++ and C extensions.

**Comment by wschwanghart** [comment]
It now worked after after reinstalling required packages and restarting R.
